server.port=${PORT_FRONTEND}

#logging
#logging.level.com.laetienda.frontend=TRACE
#logging.level.org.springframework.security=DEBUG
#logging.level.root=DEBUG

#Oath2 security
spring.security.oauth2.client.registration.keycloak.provider=keycloaket
spring.security.oauth2.client.registration.keycloak.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.keycloak.client-id=${KC_FRONTEND_CLIENT_ID}
spring.security.oauth2.client.registration.keycloak.client-secret=${KC_FRONTEND_CLIENT_ENC_PASSWORD}
spring.security.oauth2.client.registration.keycloak.scope=openid,profile
spring.security.oauth2.client.provider.keycloaket.issuer-uri=${api.kc.realm.uri}
spring.security.oauth2.client.provider.keycloaket.user-name-attribute=preferred_username

management.endpoints.web.exposure.include=health,shutdown
management.endpoint.shutdown.enabled=true
management.endpoint.health.enabled=true

#Session authentication
#spring.session.store-type=jdbc
#spring.session.jdbc.initialize-schema=never
#spring.datasource.driver-class-name=org.postgresql.Driver
#spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/springsession
#spring.datasource.username=springsession
#spring.datasource.password=ENC(WGZeD91566uwkJCCGLdLNxHoc+yw46OSjl+OMYNcSo58rYhczVSpbAWKHEVMx9BR)

#API
#user.api
api.user=http://localhost:8081/api/v0/user
api.user.create=${api.user}/create.html
api.user.findall = ${api.user}/users.html
api.user.remove = ${api.user}/delete.html?username={username}
api.user.authenticate=${api.user}/authenticate.html

#group.api
api.group=http://localhost:8081/api/v0/group
api.group.findall=${api.group}/groups.html
api.group.find=${api.group}/group.html?name={groupname}
api.group.update=${api.group}/update.html?name={groupname}
api.group.remove.member=${api.group}/removeMember.html?user={username}&group={gname}
api.group.remove.owner=${api.group}/removeOwner.html?user={username}&group={gname}
api.group.add.member=${api.group}/addMember.html?user={username}&group={gname}
api.group.add.owner=${api.group}/addOwner.html?user={username}&group={gname}