api:
  kc:
    admin:
      user:
        byUsername: ${api.kc.admin}/users?username={username}&exact=true
        byUserId: ${api.kc.admin}/users/{userId}
  kcUser:
    server: http://etuser:${PORT_USUARIO}
    folder: /api/v0/user
    find:
      file: find
      uri: ${api.kcUser.uri.folder}/${api.kcUser.find.file}
    token:
      file: token
      uri: ${api.kcUser.uri.folder}/${api.kcUser.token.file}
      path: ${api.kcUser.folder}/${api.kcUser.token.file}
    actuator:
      path: /actuator
      uri: ${api.kcUser.server}${api.kcUser.actuator.path}
      health:
        file: health
        uri: ${api.kcUser.actuator.uri}/${api.kcUser.actuator.health.file}
    login:
      file: login
      uri: ${api.kcUser.uri.folder}/${api.kcUser.login.file}
    isUsernameValid:
      file: /isUsernameValid/{username}
      uri: ${api.kcUser.uri.folder}${api.kcUser.isUsernameValid.file}
    isUserIdValid:
      file: /isUserIdValid/{userId}
      uri: ${api.kcUser.uri.folder}${api.kcUser.isUserIdValid.file}
    file:
      findEmailAddress: /findEmailAddress/{userId}
      create: /create
      userIdExists: /userIdExists/{userId}
      enable: /enable/{userId}
      delete: /delete/{userId}
    uri:
      folder: ${api.kcUser.server}${api.kcUser.folder}
      findEmailAddress: ${api.kcUser.uri.folder}${api.kcUser.file.findEmailAddress}
      create: ${api.kcUser.uri.folder}${api.kcUser.file.create}
      userIdExists: ${api.kcUser.uri.folder}${api.kcUser.file.userIdExists}
      enable: ${api.kcUser.uri.folder}${api.kcUser.file.enable}
      delete: ${api.kcUser.uri.folder}${api.kcUser.file.delete}
    path:
      login: ${api.kcUser.folder}/${api.kcUser.login.file}
      find: ${api.kcUser.folder}/${api.kcUser.find.file}
      delete: ${api.kcUser.folder}${api.kcUser.file.delete}
  mail:
    url: http://etmail:${PORT_MESSENGER}
    folder: /api/v0/email
    file:
      test: test
      send: send
    uri:
      folder: ${api.mail.url}${api.mail.folder}
      test: ${api.mail.uri.folder}/${api.mail.file.test}
      send: ${api.mail.uri.folder}/${api.mail.file.send}
  company:
    url: http://company:${PORT_COMPANY}
    folder: /api/v0/company
    uri: ${api.company.url}${api.company.folder}
    create:
      file: create
      uri: ${api.company.uri}/${api.company.create.file}
    isValid:
      file: isValid/{companyId}
      uri: ${api.company.uri}/${api.company.isValid.file}
    find:
      file: find/{id}
      uri: ${api.company.uri}/${api.company.find.file}
    findByName:
      file: findByName/{name}
      uri: ${api.company.uri}/${api.company.findByName.file}
    update:
      file:
        name: update/{companyId}/name/{value}
        description: update/{companyId}/description
#        memberPolicy: update/{companyId}/memberPolicy/{value}
      uri:
        name: ${api.company.uri}/${api.company.update.file.name}
        description: ${api.company.uri}/${api.company.update.file.description}
#        memberPolicy: ${api.company.uri}/${api.company.update.file.memberPolicy}

#      file: update
#      uri: ${api.company.uri}/${api.company.update.file}
    delete:
      file: delete/{id}
      uri: ${api.company.uri}/${api.company.delete.file}
    manager:
      file:
        add: /{companyId}/manager/add/{userId}
        remove: /{companyId}/manager/remove/{userId}
      uri:
        add: ${api.company.uri}${api.company.manager.file.add}
        remove: ${api.company.uri}${api.company.manager.file.remove}
    member:
      find:
        file: member/find/{companyId}/{userId}
        uri: ${api.company.uri}/${api.company.member.find.file}
      add:
        file: member/add/{companyId}/{userId}
        uri: ${api.company.uri}/${api.company.member.add.file}
      update:
        file: member/update
        uri: ${api.company.uri}/${api.company.member.update.file}
      delete:
        file: member/delete/{companyId}/{userId}
        uri: ${api.company.uri}/${api.company.member.delete.file}
    friend:
      file:
        find: friend/{companyId}/{userId}
        add: friend/add/{companyId}/{userId}
        accept: friend/accept/{companyId}/{userId}
        block: friend/block/{companyId}/{userId}
        unblock: friend/unblock/{companyId}/{userId}
      uri:
        find: ${api.company.uri}/${api.company.friend.file.find}
        add: ${api.company.uri}/${api.company.friend.file.add}
        accept: ${api.company.uri}/${api.company.friend.file.accept}
        block: ${api.company.uri}/${api.company.friend.file.block}
        unblock: ${api.company.uri}/${api.company.friend.file.unblock}